# 3.6: Use the oldest supported Python version.
# https://devguide.python.org/#status-of-python-branches
# 3.8: pyp4 requires python3.8
image: python:3.8

before_script:
  - python3 -m pip install virtualenv
  - if [ ! -d venv ]; then python3 -m virtualenv venv; fi
  - source venv/bin/activate
  - sed -i "s|ssh://git|https://${pyp4_username}:${pyp4_token}|g" pyproject.toml
  - make dependencies
  - make dependencies.dev

.default:
  only:
    - main
    - merge_requests
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - venv/
    policy: pull-push

stages:
  - test
  - lint

tests:
  extends: .default
  stage: test
  script: make tests COVREP=
  artifacts:
    paths:
      - .coverage
    expire_in: 1 week
  needs: []

coverage:
  extends: .default
  stage: test
  script: make coverage MINCOV=100
  needs: ["tests"]

examples:
  extends: .default
  stage: test
  script: make examples
  needs: []

flake8:
  extends: .default
  stage: lint
  script: make flake8
  needs: []

pylint:
  extends: .default
  stage: lint
  script: make pylint
  needs: []
